[package]
name = "socksx"
version = "0.1.0"
description = "A SOCKS toolkit for Rust"
authors = ["Onno Valkering"]
edition = "2018"
license = "MIT"

[dependencies]
anyhow = "1"
libc = "0.2"
log = "0.4"
nix = "0.19"
tokio = { version = "1", features = ["full"] }

[dev-dependencies]
clap = "2"
