[package]
name = "socksx"
version = "0.1.0"
authors = ["Onno Valkering"]
edition = "2018"

[dependencies]
anyhow = "1"
libc = "0.2"
log = "0.4"
nix = "0.19"
tokio = { version = "1", features = ["full"] }

[dev-dependencies]
env_logger = "0.8"