# Example of using a standalone proxy to forward traffic to a destination

version: '3.8'

services:
  proxy:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "1080:1080"
    command: "--host 0.0.0.0 --port 1080"
    networks:
      net:
        ipv4_address: 172.16.238.2

  # this will be the destination
  netcat:
    image: busybox
    command: "nc -l -p 12345"
    ports:
      - "12345:12345"
    restart: always
    networks:
      net:
        ipv4_address: 172.16.238.3

networks:
    net:
        ipam:
            driver: default
            config:
                - subnet: "172.16.238.0/24"
