name: Release

on:
  create: 
    tags:
      - 'v*'

jobs: 
  build-image:
    runs-on: ubuntu-latest
    steps:
      - name: Get Github tag
        id: meta
        run: |
          echo "::set-output name=tag::${GITHUB_REF#'refs/tags/v'}"

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
   
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push 'socksx'
        uses: docker/build-push-action@v2
        with:
          file: Dockerfile
          push: true
          tags: ghcr.io/onnovalkering/socksx:${{ steps.meta.outputs.tag }}

  create-release:
    runs-on: ubuntu-latest
    needs:
      - build-image
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        
      - name: Create release
        uses: anton-yurchenko/git-release@v3
        env:
          ALLOW_TAG_PREFIX: "true"
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
